# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: LDAP-Auth Plugin v$NEXT_MAJOR_VERSION
tag-template: v$NEXT_MAJOR_VERSION
# Uses a more common single-digit versioning in Jellyfin plugins. Can be replaced by semver: $MAJOR.$MINOR.$PATCH
version-template: $MAJOR

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: ":boom: Breaking changes"
    labels:
      - breaking
  - title: 🚨 Removed
    label: removed
  - title: ":tada: Major features and improvements"
    labels:
      - major-enhancement
  - title: 🐛 Major bug fixes
    labels:
      - major-bug
  - title: ⚠️ Deprecated
    label: deprecated
  - title: 🚀 New features and improvements
    labels:
      - enhancement
      - feature
  - title: 🐛 Bug Fixes
    labels:
      - bug
      - fix
      - bugfix
      - regression
  # Default label used by Dependabot
  - title: 📦 Dependency updates
    label: dependencies
  - title: 📝 Documentation updates
    label: documentation
  - title: 🚦 Tests
    labels:
      - test
      - tests
exclude-labels:
  - reverted
  - no-changelog
  - skip-changelog
  - invalid

template: |
  <!-- Optional: add a release summary here -->
  $CHANGES

replacers:
  - search: '@dependabot-preview'
    replace: '@dependabot'
